name: Deployment

on:
  push:
    branches:
      - master

jobs:
  pypi:
    name: Pypi
    uses: Bernardo-MG/github-workflow/.github/workflows/python_deploy_pypi.yml@v1
    secrets:
      username: ${{ secrets.DEPLOY_USER }}
      password: ${{ secrets.DEPLOY_PASSWORD }}
