name: Tests and docs

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    uses: Bernardo-MG/github-workflow/.github/workflows/python_testing.yml@develop

  deploy_develop_docs:
    name: Deploy development docs
    needs: tests
    uses: Bernardo-MG/github-workflow/.github/workflows/python_deploy_site.yml@develop
    with:
      branch: develop
      host: docs.bernardomg.com
    secrets:
      url: ${{ secrets.DEPLOY_DOCS_DEVELOP_SITE }}
      port: ${{ secrets.DEPLOY_DOCS_DEVELOP_PORT }}
      path: ${{ secrets.DEPLOY_DOCS_DEVELOP_PATH }}
      username: ${{ secrets.DEPLOY_DOCS_DEVELOP_USER }}
      password: ${{ secrets.DEPLOY_DOCS_DEVELOP_PASSWORD }}

  deploy_docs:
    name: Deploy docs
    needs: tests
    uses: Bernardo-MG/github-workflow/.github/workflows/python_deploy_site.yml@develop
    with:
      branch: master
      host: docs.bernardomg.com
    secrets:
      url: ${{ secrets.DEPLOY_DOCS_SITE }}
      port: ${{ secrets.DEPLOY_DOCS_PORT }}
      path: ${{ secrets.DEPLOY_DOCS_PATH }}
      username: ${{ secrets.DEPLOY_DOCS_USER }}
      password: ${{ secrets.DEPLOY_DOCS_PASSWORD }}